### ISSUE TITLE
Please create a jsfiddle that shows how to use it

### ISSUE THREAD

**Issue by Meai1** [gullerya/object-observer-js#5]
Makes it easier.. I guess this is just a suggestion, but trying out if something works for me is a lot of work when you look for libraries.

I tried hooking your library up to some dom elements somehow, not sure how to do it:

http://jsfiddle.net/djthkd6L/1

for example in your sample:
```
var order = { type: 'book', pid: 102, ammount: 5, remark: 'remove me' },
	observableOrder;
observableOrder = Observable.from(order);
observableOrder.observe(changes => {
	changes.forEach(change => {
		console.log(change);
	});
});
observableOrder.ammount = 7;		// { type: 'update', path: ['ammount'], value: 7, oldValue: 5 }
observableOrder.address = {			// { type: "insert", path: ['address'], value: { ... } }
	street: 'Str 75',
	apt: 29
};
observableOrder.address.apt = 30;	// { type: "update", path: ['address','apt'], value: 30, oldValue: 29 }
delete observableOrder.remark;		// { type: "delete", path: ['remark'], oldValue: 'remove me' }

```
this wont actually update the `order` object... and the change events dont even tell me which object was the original object, which I assume I'd have to update myself during the callback? Is that correct?
still leaves open how to make all this work with html elements

**Comment by gullerya** [comment]
First, thanks for the suggestion, i've added a simple fiddle with some remarks about the flow, what does what and expectations, it is [here](https://jsfiddle.net/gullerya/5a4tyoqs).

Regarding your question above specifically - yes, the observable is created by __cloning__ the original object (`order` in your case), and changes made to that are not propagated.

This library should be useful in the following Data Flow design (or similar to that):
- in service oriented application (where each data kind/piece is managed by specific service)
- the service would fetch the data from server and create observable from it
- all parts of the application would see/read/present/modify this observable clone
- all parts of the application that are interested in tracking the changes would observe the observable (either directly or via the service)

Original object becomes not interesting, except the case where you'd like to have an option to revert the changes (and even this one is better to perform other way).

Regarding HTML elements - these ones are __not__ meant to be observed by this framework, there is a native `MutationObserver` which does it perfectly.

Finally, if you are looking from something like dual binding - then I've created another library which is powered by this `object-observer-js` one, but in addition does exactly the ties between an observed data and the HTML presentation of it. You may look at it [here](https://github.com/gullerya/data-tier). It alse lacks jsFiddle, meanwhile at least :) :)

**Comment by Meai1** [comment]
ah very cool, I tried the example. The longer one prints out an error to the console btw. (the one with the russian text). 
It doesn't feature two-way binding, is there a sample somewhere? That's the one that is tricky to get right.
Btw, if I may ask: What's your opinion on the virtualdom libraries, if I understand correctly then they are essentially competitors to data-tie right? It's like angular vs. react.
I googled virtualdom and found http://maquettejs.org/ 
Likewise this is a good overview of the approaches I think: http://stackoverflow.com/questions/21109361/why-is-reacts-concept-of-virtual-dom-said-to-be-more-performant-than-dirty-mode
It seems that there are two schools of thought, either doing databinding like you are doing via attributes on regular html or creating some kind of virtual dom. Both are able to do two-way binding, although it's very hard to figure out who is doing what because then there is this new paradigm where people only want one-way flow and use some kind of flux architecture apparently.
The virtualdom approach seems to either have some kind of renderloop (unlikely?) or use events everywhere as well like you but in addition to that, they update their virtualdom representation first and then batch the changes in order to possibly make the html change faster overall.

I'm really confused on which one the best approach is... right now virtualdom is very 'in' but I think it's overly complicated to create your dom in the jsx/hyperscript way.

**Comment by gullerya** [comment]
From simple to hardest =>

I've just tried the longer example to validate it and it looks fine to me, this is the [fiddle](http://jsfiddle.net/96zbzxau/1/) of it, if you find any problem with it yet - i'd be glad for input since having just few examples makes them extremely important :)

Regarding the `checkbox` - I confirm that there is some mess there with the value (the tying is working since i do see changes on observable, but the value is not picked up correctly), I've opened [this](https://github.com/gullerya/data-tier/issues/6) issue to track is and will push the fix ASAP.

Regarding the architecture in general: agree, that in principal all of us are doing kind of dual binding (although react people would object now).
My approach is to not generate HTML syntax within JS, but keep it in really HTML fragments. It indeed looks cumbersome and conceptually wrong to me, not to mention that 'compiling on the fly enriched HTML syntax' requires from framework to support all of HTML features symmetrically which inevitable brings to limitations or hacks or simply huge and heavy implementation (symptom of this kind of weakness is React's special treatment of className stuff). So I prefer things to be separated, HTML apart and JS apart: no HTML rendering, no compiling, no 'read all innerHTML, parse and replace/build whatever' goodies, no strange mixed syntax etc.
Regarding performance - since data changes detection stays in the heart of all those frameworks - this becomes a real game changer of how the data is managed. And if Angular gave full observation model, but very unperformant, memory consuming and deterministically async (thus introducing it's own application lifecycle - digest loop, thus bringing the full cloning of every DOM event within the framework, thus - requiring to subject all application components to live within the framework etc), React/Redux from the other hand outloaded all this burden to consumer - it's now our responsibility to make changes to model, clone is correctly, catch the new data in events on the other side and rebuild the UI - deterministic, performant but cumbersome with regard to data management, in addition to the things I've not liked in the JSX. 

My take in the `data-tier` was: having real object observer (no dirty check, no performance penalties) let's provide the full data-binding in kind of Angular's way, keeping the HTML's syntax clean and standard, no magic, purely event driven etc. Of course, I had to pay somewhere else, there where the __paths__ and the __rules__ come in, but IMHO as of now it still looks to me like a decent compromise between the functionality and the learning curve, on one axis, and separation between declarative and functional part on another.

Last but not least, I do think that WebComponents with custom elements are the way the Web should/will go and it feels to me that virtual DOM approaches are not in tact with this melody, partially overlapping it, partially contradict, definitely not extensible to support OOTB any new component to come (assume that you have some non standard property on your component, be it reflected in attributes or not, how would virtual DOM engine react on this properly not even being familiar with? - wrappers, right, but that's just wrong).
